### ISSUE TITLE
[OSError] visdom fails to start

### ISSUE THREAD

**Issue by SanderGielisse** [facebookresearch/visdom#195] opened 2017-11-04 01:54 UTC
When simply executing python -m visdom.server in CMD, I get the following error.

`C:\Users\sande>python -m visdom.server
Traceback (most recent call last):
  File "C:\Users\sande\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python35\lib\site-packages\visdom\server.py", line 636, in <module>
    download_scripts()
  File "C:\Users\sande\AppData\Local\Programs\Python\Python35\lib\site-packages\visdom\server.py", line 616, in download_scripts
    with open(filename, 'wb') as fwrite:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\sande\\AppData\\Local\\Programs\\Python\\Python35\\lib\\site-packages\\visdom/static/fonts/glyphicons-halflings-regular.eot?#iefix'
`

Running;
Window 10.1.
Python 3.5.2.
Visdom 0.1.6.1.

**Comment by lvdmaaten** [comment] 2017-11-04 04:44
Can you confirm for me that folder `C:\\Users\\sande\\AppData\\Local\\Programs\\Python\\Python35\\lib\\site-packages` exists?

I think the issues is that we use Linux-style path notation here: https://github.com/facebookresearch/visdom/blob/master/py/server.py#L611

We should have used something like `os.path.join` instead. I will try to push a fix soon.

**Comment by SanderGielisse** [comment] 2017-11-04 13:08
@lvdmaaten 

The folder
`C:\Users\sande\AppData\Local\Programs\Python\Python35\Lib\site-packages`
Does exist, please note the capital of 'Lib', not sure if this is a problem.

Thanks a lot!

**Comment by dominikandreas** [comment] 2017-11-07 11:55
The problem is that windows doesn't allow "?" in filenames. A quick fix for windows users would be to delete the corresponding entry in ``ext_files`` in server.py 
```python
        '%sfonts/glyphicons-halflings-regular.eot?#iefix' % bb:
            'glyphicons-halflings-regular.eot?#iefix',
```
(lines 568-569)

@lvdmaaten Since this seems to correspond to internet explorer only, this should be an acceptable change right? I'll go ahead and create a pull request

**Comment by lvdmaaten** [comment] 2017-11-07 15:13
Ah good catch! Ironic that a fix for Internet Explorer is breaking visdom on Windows... :)

Yes, let's remove this entry for now and encourage folks to use visdom in Chrome / Firefox / etc. Looking forward to your PR!

**Comment by JackUrb** [comment] 2017-11-17 16:51
Closing as the ironic fix for this has already landed and is now in the pip version

**Closed by JackUrb** 2017-11-17 16:51 UTC
