### ISSUE TITLE
Visdom server incompatible with tornado v5.0+

### ISSUE THREAD

**Issue by dizcza** [facebookresearch/visdom#312] opened 2018-04-14 10:36 UTC
```bash
pip install --upgrade -e git+https://github.com/facebookresearch/visdom.git@master#egg=visdom
pip list | grep visdom  # visdom (0.1.7.2)
python -V  # Python 3.6.4 :: Anaconda, Inc.
python -m visdom.server
```
```python
Traceback (most recent call last):
  File "/home/dizcza/anaconda3/envs/mcmc/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dizcza/anaconda3/envs/mcmc/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dizcza/PycharmProjects/MCMC_BinaryNet/src/visdom/py/visdom/server.py", line 29, in <module>
    ioloop.install()  # Needs to happen before any tornado imports!
  File "/home/dizcza/anaconda3/envs/mcmc/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
```
tornado v5.0+ fails
tornado v4.5.3 works fine

**Comment by JackUrb** [comment] 2018-04-16 16:06
Ack I suppose tornado made a breaking change - I'll see what happened

**Comment by JackUrb** [comment] 2018-04-16 23:14
Hi @dizcza - It appears tornado's interaction with ioloop has changed for python 3.6, can you try running the server when omitting lines 27 and 29? Tornado's ioloop now seems to be backed by asyncio in python 3, which would make this install potentially redundant or cause unexpected behavior.

**Comment by JackUrb** [comment] 2018-04-17 16:05
Sorry for the bother, other things on my plate right now - thought you'd be able/willing to help out but I mis-assessed. I'll get to it sometime soon

**Comment by malmaud** [comment] 2018-06-22 19:53
Was this fixed at some point? I was going to look into fixing it, but visdom master and tornado 5.0.2 is working fine already.

**Comment by JackUrb** [comment] 2018-06-22 20:08
Oh is it? I suppose tornado restored the original capabilities. I'll close this out. Thanks for the heads up!

**Closed by JackUrb** 2018-06-22 20:08 UTC
Labels: bug, dependencies

**Comment by vikasTmz** [comment] 2018-10-03 13:50
If you are using tornado v5.0+, you need to upgrade pyzmq to v17.
[credits @takluyver, from [https://github.com/jupyter/notebook/issues/3595](https://github.com/jupyter/notebook/issues/3595)]
