### ISSUE TITLE
Exception thrown in visdom server, resulting in reported 'Offline' status for chart viewers

### ISSUE THREAD

**Issue by sdraper-CS** [facebookresearch/visdom#303] opened 2018-03-20 21:21 UTC
I have been using Visdom for a while without issues.  However, after adding several new charts to an environment I started getting an `KeyError` thrown by `server.py` frequently.  The stack dump is as follows:
```
3/20/2018 3:45:35 PMERROR:tornado.application:Uncaught exception POST /env/Metrics%20(detailed) (10.42.128.115)
3/20/2018 3:45:35 PMHTTPServerRequest(protocol='http', host='10.63.3.28:8097', method='POST', uri='/env/Macys-Pros%20(detailed)', version='HTTP/1.1', remote_ip='10.42.128.115', headers={'Host': '10.63.3.28:8097', 'Content-Length': '24', 'Accept': '*/*', 'Origin': 'http://10.63.3.28:8097', 'X-Requested-With': 'XMLHttpRequest', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', 'Referer': 'http://10.63.3.28:8097/', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,en;q=0.9', 'X-Forwarded-Port': '8097', 'X-Forwarded-For': '10.50.1.131', 'Connection': 'close'})
3/20/2018 3:45:35 PMTraceback (most recent call last):
3/20/2018 3:45:35 PM  File "/opt/conda/envs/c12e-visdom/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute
3/20/2018 3:45:35 PM    result = method(*self.path_args, **self.path_kwargs)
3/20/2018 3:45:35 PM  File "/opt/conda/envs/c12e-visdom/lib/python3.6/site-packages/visdom/server.py", line 612, in post
3/20/2018 3:45:35 PM    load_env(self.state, args, self.subs[sid])
3/20/2018 3:45:35 PMKeyError: '360ead0e5f8678'
3/20/2018 3:45:35 PMERROR:root:ERROR: 500: {'exc_info': (<class 'KeyError'>, KeyError('360ead0e5f8678',), <traceback object at 0x7f58b25d7348>)}
3/20/2018 3:45:35 PMERROR:tornado.access:500 POST /env/Metrics%20(detailed) (10.42.128.115) 1.98ms
```
 I am using Visdom 0.1.7, installed by building a conda environment from this `environment.yaml`:
```
name: c12e-visdom
dependencies:
- python=3.6
- pip:
  - visdom
```
The symptom visible to users of the server (browser side) is that the server shows as 'Offline' (in the indicator top right of the Visdom-rendered webpage), and clicking this brings it back on-line apparently with everything rendered correctly.  Currently the charts are being updated every 5 minutes, and the fault seems to occur erratically (certainly not on every chart-update pas).  Currently the charts are being fully re-constructed each time (not iteratively updated)

**Comment by JackUrb** [comment] 2018-03-21 14:24
Hi @sdraper-CS - This bug seems to be caused by a websocket being dropped but not removed from the subscriptions. It's possible this issue no longer exists on 1.7.2 however, so I don't know if I'll be albe to track it down directly.

**Comment by sdraper-CS** [comment] 2018-03-21 17:59
@JackUrb When you mention 1.7.2 I assume you mean of Visdom? (0.1.7.2??)  If so is this version reasonably stable (and reasonably backward compatible at the API usage level for the stats generator)?  Can you confirm that the pip dependency would presumably be:
```
- pip:
  - visdom=0.1.7.2
```

**Comment by JackUrb** [comment] 2018-03-21 19:59
@sdraper-CS I haven't released it on pip yet b/c it breaks under certain kinds of proxies and I'm still fixing that issue. It's the version you can install from the source here on GitHub, and the fix for your current issue will be released on Pip in the same release that includes the fix to the proxy issue.

**Closed** 2018-05-02 17:11 UTC
Labels: bug, hi-pri, reproduced
