### ISSUE TITLE
Cannot expand figures to the bottom when figure at the bottom of the page

### ISSUE THREAD

**Issue by rooa** [facebookresearch/visdom#74] opened 2017-04-30 18:23 UTC
There is an issue of not being able to expand a figure vertically when it is at the bottom of the page. I have tested on Safari and Chrome on macOS.

Please see the gif of the bottom of the page below: 
![](https://i.gyazo.com/6c6a0e7b312ddf9aa62b11335cb6976b.gif)
I cannot expand at some point as it shows.

**Comment by JackUrb** [comment] 2017-10-12 15:20
Hi @rooa: I'm trying to reproduce your issue, however I'm only running into it when the browser window itself is at the bottom of my screen. If the browser window is not at the bottom of my monitor I'm able to extend the figure below the page. Are you able to reproduce it in any circumstance other than having the browser window at the bottom of your monitor?

**Comment by JackUrb** [comment] 2017-11-17 16:43
Closing as it has been more than a month and I can't reproduce the issue

**Closed by JackUrb** 2017-11-17 16:43 UTC
