### ISSUE TITLE
Uncaught TypeError: Cannot read property 'content' of null , no plots show up.

### ISSUE THREAD

**Issue by aman-tiwari** [facebookresearch/visdom#118] opened 2017-07-17 20:18 UTC
```js
main.js?v=1dec754…:1 Uncaught TypeError: Cannot read property 'content' of null
    at t.r.processPane (main.js?v=1dec754…:1)
    at main.js?v=1dec754…:1
    at Array.forEach (<anonymous>)
    at r.processBatchedPanes (main.js?v=1dec754…:1)
```

Getting this error in the JS console when opening `http://localhost:8097/`. None of my plots show up, even though the log printed by the server process shows that it should have been updated.

```
(py3k) a, 11:53, ~, python -m visdom.server
It's Alive!
INFO:tornado.access:304 GET / (127.0.0.1) 2.53ms
INFO:tornado.access:101 GET /socket (127.0.0.1) 0.42ms
Opened new socket from ip: 127.0.0.1
INFO:tornado.access:200 POST /env/main (127.0.0.1) 457.45ms
INFO:tornado.access:200 GET /favicon.png (127.0.0.1) 1.46ms
INFO:tornado.access:200 POST /events (127.0.0.1) 0.48ms
INFO:tornado.access:200 POST /events (127.0.0.1) 0.42ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.49ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.43ms
INFO:tornado.access:200 POST /events (127.0.0.1) 2.33ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.46ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.42ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.51ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.46ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.51ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.48ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.45ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.44ms
INFO:tornado.access:200 POST /events (127.0.0.1) 1.81ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.48ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.46ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.48ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.42ms
INFO:tornado.access:304 GET / (127.0.0.1) 1.28ms
INFO:tornado.access:101 GET /socket (127.0.0.1) 0.35ms
Opened new socket from ip: 127.0.0.1
INFO:tornado.access:200 POST /env/main (127.0.0.1) 482.20ms
INFO:tornado.access:200 GET /favicon.png (127.0.0.1) 1.58ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.53ms
INFO:tornado.access:200 POST /update (127.0.0.1) 0.61ms
INFO:tornado.access:200 POST /events (127.0.0.1) 2.04ms
...etc...
```
The code to create the plots is something like:
```python
self.vis = visdom.Visdom()
self.loss_window = self.vis.scatter(X=np.asarray([[0.0, 0.0]]), opts={'title': 'loss'})
self.loss_ema_window = self.vis.scatter(X=np.asarray([[0.0,0.0]]), opts={'title': 'loss_ema'})

for etc in data:
    ... do stuff ...
    self.vis.updateTrace(np.asarray([x]), np.asarray([loss.data[0]]), self.loss_window, append=True)
    self.vis.updateTrace(np.asarray([x]), np.asarray([loss_ema]), self.loss_ema_window, append=True)
        
    to_vis.size() == torch.Size([16, 3, 256, 512])
    self.vis.images(to_vis.numpy(), opts=dict(title=str(batch_idx) + '_' + str(epoch)))

```

**Comment by ajabri** [comment] 2017-07-17 20:21
Can you try `clear`ing your env from the browser?

**Comment by aman-tiwari** [comment] 2017-07-17 20:26
That doesn't seem to change anything

**Comment by ajabri** [comment] 2017-09-05 04:43
In the above I mean `clear` and then reload your page.

**Comment by JackUrb** [comment] 2017-12-13 16:09
Closing as I don't have enough context to reproduce and it's been a long time since the bug was opened (and we might've even fixed this issue, updateTrace is no longer used for instance).

**Closed by JackUrb** 2017-12-13 16:09 UTC
