### ISSUE TITLE
sortLayoutItemsByRowCol error

### ISSUE THREAD

**Issue by FlyingRoastDuck** [facebookresearch/visdom#207] opened 2017-11-22 13:58 UTC
```
main.js?v=9365dbc3fbe4d5345dc312c71128631e:1 Uncaught TypeError: Cannot read property 'sortLayoutItemsByRowCol' of undefined
    at Object.<anonymous> (main.js?v=9365dbc3fbe4d5345dc312c71128631e:1)
    at t (main.js?v=9365dbc3fbe4d5345dc312c71128631e:1)
    at Object.<anonymous> (main.js?v=9365dbc3fbe4d5345dc312c71128631e:1)
    at t (main.js?v=9365dbc3fbe4d5345dc312c71128631e:1)
    at main.js?v=9365dbc3fbe4d5345dc312c71128631e:1
    at main.js?v=9365dbc3fbe4d5345dc312c71128631e:1
```
Getting this error in the JS console when opening http://localhost:8097/. None of my plots show up.
By the way, I changed line 27~35 of index.html in {$Anaconda3path}\Lib\site-packages\visdom\static like this for some known reasons(I'm in China and I've confirmed that all dependencies that https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md mentioned are included in my directory)...:
```
	<script src="https://unpkg.com/react@15/dist/react.min.js"></script>
	<script src="https://unpkg.com/react-dom@15/dist/react-dom.min.js"></script>
	<script src="https://unpkg.com/classnames@2.2.5"></script>
	<script src="https://unpkg.com/layout-bin-packer@1.2.2"></script>
	<script src={{ static_url("js/react-grid-layout-stable/dist/react-grid-layout.min.js") }}></script>

	<!-- Mathjax -->
	<script type="text/javascript" async src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_SVG"></script>



    <!-- Plotly -->
    <script src={{ static_url("js/plotly.js-master/dist/plotly.min.js") }}></script>
```
It seems that the problem lies in react-grid-layout package but I don't know how to solve it.
log infomation in cmd are listed below:
```
It's Alive!
INFO:root:Application Started
You can navigate to http://localhost:8097
INFO:tornado.access:200 GET / (::1) 11.00ms
INFO:tornado.access:200 GET /static/js/main.js?v=9365dbc3fbe4d5345dc312c71128631e (::1) 192.14ms
WARNING:tornado.access:404 GET /static/css/bootstrap.min.css.map (::1) 1.00ms
INFO:tornado.access:200 GET /favicon.png (::1) 3.00ms
INFO:tornado.access:304 GET / (::1) 3.01ms
WARNING:tornado.access:404 GET /static/css/bootstrap.min.css.map (::1) 0.00ms
INFO:tornado.access:200 GET /favicon.png (::1) 4.00ms
```

**Comment by FlyingRoastDuck** [comment] 2017-11-22 14:06
visdom version:0.1.6.3
OS:win 10
browser:chrome 62.0.3202.94

**Comment by JackUrb** [comment] 2017-11-22 14:15
Your javascript dependancies seem to be fine, but it seems you're missing [bootstrap css dependancies](https://unpkg.com/bootstrap@3.3.7/dist/css/bootstrap.min.css).
```
WARNING:tornado.access:404 GET /static/css/bootstrap.min.css.map (::1) 1.00ms
```
It's possible that getting these will solve the problem

**Comment by FlyingRoastDuck** [comment] 2017-11-22 14:32
Thank you, I've tried this and now, no 404 message are listed in my CMD window, but there are no figure
in browser. It doesn't work

**Comment by JackUrb** [comment] 2017-11-22 14:38
Alright so now the issue is on the frontend side - can you list the contents of your javascript console in your browser?

**Comment by FlyingRoastDuck** [comment] 2017-11-23 00:03
```
Uncaught TypeError: Cannot read property 'sortLayoutItemsByRowCol' of undefined
    at Object.<anonymous> (main.js:1)
    at t (main.js:1)
    at Object.<anonymous> (main.js:1)
    at t (main.js:1)
    at main.js:1
    at main.js:1
```
The error in JS console seems to have something to do with main.js in {#anaconda3Path}\Lib\site-packages\visdom\static\js\main.js and the console reports "Cannot read property 'sortLayoutItemsByRowCol' of undefined"

**Comment by FlyingRoastDuck** [comment] 2017-11-23 00:04
python version:3.5.2

**Comment by FlyingRoastDuck** [comment] 2017-11-23 05:08
![qq 20171123130737](https://user-images.githubusercontent.com/29745430/33159613-72a7f000-d04f-11e7-8aaa-151e78a2c9a1.png)

**Comment by FlyingRoastDuck** [comment] 2017-11-24 04:24
Is there anyone knowing how to solve the problem?

**Comment by JackUrb** [comment] 2017-11-26 18:23
The issue appears to be that the correct ReactGridLayout package is never actually being properly loaded. The type error is due to the line in main.js:
```
const sortLayout = ReactGridLayout.utils.sortLayoutItemsByRowCol;
```
meaning this is failing at the import step. Specifically ReactGridLayout is missing the utils module, which was introduced in 2016. You're somehow using an older package. Thus the version being loaded in:
```
<script src={{ static_url("js/react-grid-layout-stable/dist/react-grid-layout.min.js") }}></script>
```
Is not correct

**Comment by FlyingRoastDuck** [comment] 2017-11-27 03:08
Thank you, your suggestion seems to be right. I downloaded the file from https://github.com/STRML/react-grid-layout/tree/stable since no react-grid-layout.min.js can be found in the  master branch. I noticed that the stable branch is updated 1 year ago. Has the stable branch been abandoned?How can I get react-grid-layout.min.js in new version?

**Comment by JackUrb** [comment] 2017-11-27 14:41
`https://cdn.rawgit.com/STRML/react-grid-layout/0.14.0/dist/react-grid-layout.min.js`, as listed in the [contributing guidelines](https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md)

**Comment by FlyingRoastDuck** [comment] 2017-11-28 00:40
![default](https://user-images.githubusercontent.com/29745430/33296671-be7fbd5c-d417-11e7-8e85-48c8cb529d17.PNG)
more errors ：(

**Comment by JackUrb** [comment] 2017-12-13 15:56
As of https://github.com/facebookresearch/visdom/pull/224 you should be able to pull the dependancies regularly without necessarily needing to download by hand.

Closing as I believe the issue is resolved and it's been 2 weeks since my last comment with no answer. Feel free to reopen if reinstalling visdom doesn't work

**Closed by JackUrb** 2017-12-13 15:56 UTC
