### ISSUE TITLE
[help wanted]  In the browser shows that mathmenu is not loaded

### ISSUE THREAD

**Issue by shaneshbi** [facebookresearch/visdom#479] opened 2018-09-19 08:46 UTC
start visdom.server,shows as bellow
![df0df4003a65c1881ce956bb3463e367](https://user-images.githubusercontent.com/39234932/45741726-e61b5780-bc2a-11e8-8343-cde065afc1c6.jpg)
GET /extensions/MathMenu from cdn(MathJax)

however,the browser turns blue, got no picture on it.
![209e31663d8733a3657df4968cfbef35](https://user-images.githubusercontent.com/39234932/45741829-267ad580-bc2b-11e8-8016-b0a88262c0c2.jpg)
![d64a14d683f06d9146ea6de875d0a2d8](https://user-images.githubusercontent.com/39234932/45741834-28449900-bc2b-11e8-95c1-a24c27059252.jpg)

when i run a test code.it cannot show the picture on browser.
![957b126b1cce726f56683223b1738d70](https://user-images.githubusercontent.com/39234932/45743069-e5d08b80-bc2d-11e8-8ceb-210b5748b9a6.jpg)

i install visdom in a proper way.
download_scripts step also completely finished.
why the brower cannot load the /extensions/MathZoom && MathMenu?
can anyone help me out?

**Comment by JackUrb** [comment] 2018-09-19 13:53
Mathmenu and mathzoom have not been loading properly since at least version 0.1.4, and maybe before that as well. This alone is not enough to prevent most of the visdom functionality from working.

You appear to be displaying a photo of plots in compare mode. If the two windows displayed don't have any plots with the same title, this view won't show anything.

**Comment by JackUrb** [comment] 2018-10-03 16:37
I'm closing this issue as I'm fairly confident your issue is caused by being in a compare view (as both `main` and `my_wind` are selected). Feel free to reopen this issue if you're still having problems after deselecting one of those.

**Closed by JackUrb** 2018-10-03 16:37 UTC

**Comment by MounaSah** [comment] 2022-02-01 11:17
Hello Shaneshbi,
Did you got a solution for your issue ?
I encountered the same problem :( Could you help me please!!
