### ISSUE TITLE
[FeatureRequest] Save contents of pane for offline plotly rendering

### ISSUE THREAD

**Issue by skrish13** [facebookresearch/visdom#126] opened 2017-08-09 11:14 UTC
If I want to save a pane, how do I do it from python? (using the pane id basically). Asking wrt saving a graph (vis.line)

I checked the demo.py, didnt really find anything relevant to this.

**Comment by ajabri** [comment] 2017-08-10 01:33
By save a pane, do you mean save the plot content to a file?

**Comment by skrish13** [comment] 2017-08-10 10:22
Yes i mean that only. Should've mentioned that, sorry.

**Comment by skrish13** [comment] 2017-08-18 06:25
@ajabri any updates?

**Comment by ajabri** [comment] 2017-08-20 18:18
Visdom wasn't really designed for that kind of use case. However, each of the data structures that are sent to the server by the python client API are compatible with Plotly's python offline plotting feature. It should be easy to add an option to simply return that data structure instead of sending it to the server, e,g, here https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L585

Then, you can use the `data` and `layout` fields with  https://github.com/plotly/plotly.py/blob/master/plotly/offline/offline.py#L385.

**Comment by JackUrb** [comment] 2018-02-07 21:37
Closing as duplicate of #232, which has more recent reflections on this

**Closed by JackUrb** 2018-02-07 21:37 UTC
Labels: enhancement
