### ISSUE TITLE
Visdome server was killed because of MemoryError

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/visdom#386] opened 2018-06-18 22:00 UTC
Run visdom with pretty intensive data load(4-5  models) and it was crashed with error after 5 days uptime:

```
ERROR:root:ERROR: 500: {'exc_info': (<class 'MemoryError'>, MemoryError(), <traceback object at 0x7f3a8f62ff08>)}
ERROR:tornado.access:500 POST /update (100.97.65.133) 225.94ms
ERROR:tornado.application:Uncaught exception POST /update (100.97.65.133)
HTTPServerRequest(protocol='http', host='100.97.69.76:8097', method='POST', uri='/update', version='HTTP/1.1', remote_ip='100.97.65.133', headers={'Host': '100.97.69.76:8097', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '539'})
Traceback (most recent call last):
  File "/private/home/maksymets/.conda/envs/my_fair_env/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/private/home/maksymets/.conda/envs/my_fair_env/lib/python3.6/site-packages/visdom/server.py", line 582, in post
    self.wrap_func(self, args)
  File "/private/home/maksymets/.conda/envs/my_fair_env/lib/python3.6/site-packages/visdom/server.py", line 575, in wrap_func
    broadcast(handler, p, eid)
  File "/private/home/maksymets/.conda/envs/my_fair_env/lib/python3.6/site-packages/visdom/server.py", line 369, in broadcast
    self.subs[s].write_message(msg)
  File "/private/home/maksymets/.conda/envs/my_fair_env/lib/python3.6/site-packages/tornado/websocket.py", line 252, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/private/home/maksymets/.conda/envs/my_fair_env/lib/python3.6/site-packages/tornado/websocket.py", line 793, in write_message
    return self._write_frame(True, opcode, message, flags=flags)
  File "/private/home/maksymets/.conda/envs/my_fair_env/lib/python3.6/site-packages/tornado/websocket.py", line 776, in _write_frame
    return self.stream.write(frame)
  File "/private/home/maksymets/.conda/envs/my_fair_env/lib/python3.6/site-packages/tornado/iostream.py", line 395, in write
    self._write_buffer += data
MemoryError
ERROR:root:ERROR: 500: {'exc_info': (<class 'MemoryError'>, MemoryError(), <traceback object at 0x7f3a902b0e48>)}
ERROR:tornado.access:500 POST /update (100.97.65.133) 230.93ms
```

**Comment by JackUrb** [comment] 2018-06-19 15:49
Hi @mathfac - thanks for reaching out and sorry that this happened! Unfortunately you probably were already running this before the introduction of https://github.com/facebookresearch/visdom/pull/375, which would let you replay your missing logs. 

I'll do a pass to see if the server might be leaking memory anywhere, hopefully something turns up, but I'm thinking the issue here is that the size of the environment containing the updated panel exceeding some un-reported cap on send size for tornado websockets.

Some follow ups that might be able to help me get to the bottom of this:
Do you happen to have the front-end logs from this crash? Are you putting different models/experiments into different environments, or just logging them all to the main env?

**Comment by mathfac** [comment] 2018-06-20 22:36
@JackUrb  thanks for the response:
>Do you happen to have the front-end logs from this crash? 

I didn't see any errors from the front UI. I will check JS console next time.
> Are you putting different models/experiments into different environments, or just logging them all to the main env?

Every model is in a separate environment, no more than 5 charts per environment.
Will double check how to save my previous data

@JackUrb what do I need to do to enable savings of logs locally? Just build fresh version of visdom?

**Comment by JackUrb** [comment] 2018-06-20 23:47
Hi @mathfac thanks for the updated info - no worries if you didn't have the logs, do keep them next time (or rather hopefully there won't be a next time).

If every model was in its own env I'm somewhat surprised it would crash with just 4 charts. How frequently were you updating? How big do you think your graphs were getting (in # of points)?

Yeah if you pull now and build from source you should be able to start saving logs. More details here: https://github.com/facebookresearch/visdom/pull/375

**Comment by JackUrb** [comment] 2018-07-18 17:30
Closing as this is essentially a duplicate of #395 at this point, for which development is underway

**Closed by JackUrb** 2018-07-18 17:30 UTC
